def stopwords():
    stopwords = [
        "a", "about", "above", "after", "again", "against", "all", "am", "an", "and",
        "any", "are", "aren't", "as", "at", "be", "because", "been", "before", "being",
        "below", "between", "both", "but", "by", "can", "cannot", "could", "couldn't",
        "did", "didn't", "do", "does", "doesn't", "doing", "don't", "down", "during",
        "each", "few", "for", "from", "further", "had", "hadn't", "has", "hasn't", "have",
        "haven't", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers",
        "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've",
        "if", "in", "into", "is", "isn't", "it", "it's", "its", "itself", "let's", "me",
        "more", "most", "mustn't", "my", "myself", "no", "nor", "not", "of", "off", "on",
        "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over",
        "own", "same", "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't",
        "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them",
        "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll",
        "they're", "they've", "this", "those", "through", "to", "too", "under", "until",
        "up", "very", "was", "wasn't", "we", "we'd", "we'll", "we're", "we've", "were",
        "weren't", "what", "what's", "when", "when's", "where", "where's", "which", "while",
        "who", "who's", "whom", "why", "why's", "with", "won't", "would", "wouldn't", "you",
        "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves",
        "u", "ur", "us", "mine", "need", "think", "always", "well", "still", "yet",
        "maybe", "probably", "actually", "seriously", "anyway", "anyways", "know",
        "honestly", "perhaps", "okay", "ok", "fine", "sure", "alright", "thanks",
        "sorta", "sort of", "basically", "generally", "mostly", "relatively",
        "obviously", "apparently", "definitely", "people", "time", "said", "didn",
        "lol", "lmao", "omg", "idk", "ikr", "tbh", "afaik", "smh", "fyi", "brb", "btw",
        "imo", "imho", "like", "just", "get", "also", "yeah", "oh", "hey", "guys",
        "thank", "pls", "please", "hi", "hello", "yay", "ugh", "wow", "hmm", "guy",
        "subreddit", "sub", "post", "posts", "op", "edit", "downvote", "upvote", "bro",
        "one", "sentence", "word", "words", "text", "will", "comment", "found", "find",
        "even", "don", "re", "repost", "aita", "ama", "new", "old", "soon", "way",
        "meirl", "irl", "thread", "reddit", "now", "got", "never", "much", "see",
        "http", "https", "www", "since", "sorry", "minutes", "minute", "sent",
        "second", "seconds", "actual", "giphy", "gif", "ve", "lot", "lots",
    ]

    return stopwords